    export const courseData = [
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Learning historical words and sentences',
      lesson: 10,
      student: 200,
      level: 'Intermediate',
      score: 4,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Learning historical words and sentences',
      lesson: 8,
      student: 180,
      level: 'Beginner',
      score: 3.5,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Learning historical words and sentences',
      lesson: 12,
      student: 250,
      level: 'Advanced',
      score: 4.8,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Learning historical words and sentences',
      lesson: 12,
      student: 250,
      level: 'Advanced',
      score: 3.8,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Learning historical words and sentences',
      lesson: 12,
      student: 250,
      level: 'Advanced',
      score: 2.8,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Learning historical words and sentences',
      lesson: 12,
      student: 250,
      level: 'Advanced',
      score: 4.8,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Introduction to Ancient Civilizations',
      lesson: 6,
      student: 150,
      level: 'Beginner',
      score: 4.2,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Medieval History Unveiled',
      lesson: 9,
      student: 220,
      level: 'Intermediate',
      score: 4.5,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'World War I: Causes and Consequences',
      lesson: 12,
      student: 300,
      level: 'Advanced',
      score: 4.9,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Renaissance Revival: Art and Culture',
      lesson: 7,
      student: 180,
      level: 'Intermediate',
      score: 4.0,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Exploring Ancient Empires',
      lesson: 10,
      student: 250,
      level: 'Advanced',
      score: 4.7,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'The Industrial Revolution: Impact and Legacy',
      lesson: 8,
      student: 200,
      level: 'Intermediate',
      score: 4.3,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Colonialism and Its Effects on Modern Society',
      lesson: 11,
      student: 280,
      level: 'Advanced',
      score: 4.6,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Middle Ages Rediscovered',
      lesson: 9,
      student: 210,
      level: 'Intermediate',
      score: 4.4,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Revolutionary Movements: Past and Present',
      lesson: 10,
      student: 240,
      level: 'Advanced',
      score: 4.8,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Cultural Evolution through the Ages',
      lesson: 8,
      student: 190,
      level: 'Intermediate',
      score: 4.1,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'Ancient Philosophies Explored',
      lesson: 7,
      student: 170,
      level: 'Beginner',
      score: 3.9,
    },
    {
      image: 'https://elearningindustry.com/wp-content/uploads/2020/11/how-to-use-animation-for-online-courses.jpg',
      title: 'The Great Wars: Clash of Ideologies',
      lesson: 12,
      student: 280,
      level: 'Advanced',
      score: 4.9,
    },
  ];